name: Shorebird Release, Development (private)
uses: dexcom-charles-tatum/shorebird-release-private@v1
with:
    flutter-version: 3.32.6
    platform: android
    working-directory: .
    args: "--flavor=development --artifact=apk"
description: Create a new release using the Shorebird CLI (private)

inputs:
  flutter-version:
    description: Flutter version to use
    required: true
  platform:
    description: Platform to release for (e.g., android, ios)
    required: true
  working-directory:
    description: Directory to run the release command in
    required: true
  args:
    description: Additional arguments to pass to shorebird release
    required: false

outputs:
  release-version:
    description: The version of the release created

runs:
  using: "composite"
  steps:
    - name: Run Shorebird Release
      run: |
        cd ${{ inputs.working-directory }}
        shorebird release ${{ inputs.platform }} \
          --flutter-version=${{ inputs.flutter-version }} \
          ${{ inputs.args }}
      shell: bash
